Initial BGFX support, Zig to 0.12.0

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -50,8 +50,8 @@ jobs:
   x86-64-linux:
     needs: ["validation"]
     name: x86-64 Linux
-    runs-on: ubuntu-latest
-    timeout-minutes: 10
+    runs-on: linux-large
+    timeout-minutes: 20
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -59,7 +59,7 @@ jobs:
           submodules: true
 
       - name: Prepare
-        run: sudo apt-get update && sudo apt-get install kcov libdbus-1-dev
+        run: sudo apt-get install kcov libdbus-1-dev
       
       - name: Read .zig-version
         id: zigversion
@@ -106,16 +106,24 @@ jobs:
       - name: Test headless standalone with asset root
         run: zig-out/bin/cetech1 --headless --max-kernel-tick 5 --asset-root fixtures/test_asset/
       
-      # TODO: make linux work in CI
-      # - name: Test UI headless 
-      #   run: zig-out/bin/cetech1 --headless --test-ui --test-ui-junit ./result.xml
-      #
+      - name: Test UI headless 
+        run: zig-out/bin/cetech1 --headless --test-ui --test-ui-junit ./result.xml
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: "./result.xml"
+          fail_on_failure: true
+          require_passed_tests: true
+          require_tests: true
+          detailed_summary: true
 
   x86-64-macos:
     needs: ["validation"]
     name: x86-64 Macos
-    runs-on: macos-latest
-    timeout-minutes: 10
+    runs-on: macos-13-large # macos-latest
+    timeout-minutes: 20
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -155,7 +163,7 @@ jobs:
 
       - name: Test unit
         run: zig-out/bin/cetech1_test
-        #run: kcov --include-pattern=cetech1/src/ kcov-output zig-out/bin/cetech1_test
+        #run: kcov --include-pattern=/cetech1/src/,/cetech/public/ kcov-output zig-out/bin/cetech1_test
 
       - name: Test headless standalone
         run: zig-out/bin/cetech1 --headless --max-kernel-tick 5 
@@ -174,20 +182,19 @@ jobs:
           fail_on_failure: true
           require_passed_tests: true
           require_tests: true
-          include_passed: true
           detailed_summary: true
 
   x86-64-windows:
     needs: ["validation"]
     name: x86-64 Windows
-    runs-on: windows-latest
-    timeout-minutes: 10
+    runs-on: windows-large # windows-latest
+    timeout-minutes: 20
     steps:
       - name: Checkout
         uses: actions/checkout@v4
         with:
           submodules: true
-
+          
       - name: Read .zig-version
         id: zigversion
         uses: juliangruber/read-file-action@v1
@@ -216,12 +223,12 @@ jobs:
           overwrite: true
           retention-days: 1
 
-      - name: configure Pagefile
-        uses: al-cheb/configure-pagefile-action@v1.4
-        with:
-          minimum-size: 8GB
-          maximum-size: 16GB
-          disk-root: "C:"
+      # - name: configure Pagefile
+      #   uses: al-cheb/configure-pagefile-action@v1.4
+      #   with:
+      #     minimum-size: 8GB
+      #     maximum-size: 16GB
+      #     disk-root: "C:"
 
       - name: Test unit
         shell: bash
