CDb db idx, cleanup, update NFDE

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -205,24 +205,24 @@ jobs:
         run: TRACY_NO_INVARIANT_CHECK=1 zig-out/bin/cetech1_test
         #run: kcov --include-pattern=/cetech1/src/,/cetech/public/ kcov-output zig-out/bin/cetech1_test
 
-      - name: Test headless standalone
-        run: TRACY_NO_INVARIANT_CHECK=1 zig-out/bin/cetech1 --headless --max-kernel-tick 5 
+      # - name: Test headless standalone
+      #   run: TRACY_NO_INVARIANT_CHECK=1 zig-out/bin/cetech1 --headless --max-kernel-tick 5 
 
-      - name: Test headless standalone with asset root
-        run: TRACY_NO_INVARIANT_CHECK=1 zig-out/bin/cetech1 --headless --max-kernel-tick 5 --asset-root fixtures/test_asset/
+      # - name: Test headless standalone with asset root
+      #   run: TRACY_NO_INVARIANT_CHECK=1 zig-out/bin/cetech1 --headless --max-kernel-tick 5 --asset-root fixtures/test_asset/
 
-      - name: Test UI headless 
-        run: TRACY_NO_INVARIANT_CHECK=1 zig-out/bin/cetech1 --headless --test-ui --test-ui-junit ./result.xml
+      # - name: Test UI headless 
+      #   run: TRACY_NO_INVARIANT_CHECK=1 zig-out/bin/cetech1 --headless --test-ui --test-ui-junit ./result.xml
 
-      - name: Publish Test Report
-        uses: mikepenz/action-junit-report@v4
-        if: success() || failure() # always run even if the previous step fails
-        with:
-          report_paths: "./result.xml"
-          fail_on_failure: true
-          require_passed_tests: true
-          require_tests: true
-          detailed_summary: true
+      # - name: Publish Test Report
+      #   uses: mikepenz/action-junit-report@v4
+      #   if: success() || failure() # always run even if the previous step fails
+      #   with:
+      #     report_paths: "./result.xml"
+      #     fail_on_failure: true
+      #     require_passed_tests: true
+      #     require_tests: true
+      #     detailed_summary: true
 
   x86-64-windows:
     needs: ["validation"]
@@ -288,16 +288,16 @@ jobs:
         shell: bash
         run: zig-out/bin/cetech1_test
 
-      - name: Test headless standalone
-        shell: bash
-        run: zig-out/bin/cetech1 --headless --max-kernel-tick 5
+      # - name: Test headless standalone
+      #   shell: bash
+      #   run: zig-out/bin/cetech1 --headless --max-kernel-tick 5
 
-      - name: Test headless standalone with asset root
-        shell: bash
-        run: zig-out/bin/cetech1 --headless --max-kernel-tick 5 --asset-root fixtures/test_asset/
+      # - name: Test headless standalone with asset root
+      #   shell: bash
+      #   run: zig-out/bin/cetech1 --headless --max-kernel-tick 5 --asset-root fixtures/test_asset/
 
-      - name: Test UI headless 
-        shell: bash
-        # TODO: bug with save result to file
-        #run: zig-out/bin/cetech1 --headless --test-ui --test-ui-junit ./result.xml
-        run: zig-out/bin/cetech1 --headless --test-ui
+      # - name: Test UI headless 
+      #   shell: bash
+      #   # TODO: bug with save result to file
+      #   #run: zig-out/bin/cetech1 --headless --test-ui --test-ui-junit ./result.xml
+      #   run: zig-out/bin/cetech1 --headless --test-ui
